[build]
  functions = "netlify/functions"
  publish = "."
  command = "# no build command needed"

[dev]
  functions = "netlify/functions"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 