name: Twitch Clips Update

on:
  schedule:
    - cron: '0 */12 * * *'  # Exécution toutes les 12 heures
  workflow_dispatch:  # Permet l'exécution manuelle
  push:
    paths:
      - 'clips.json'

jobs:
  update-clips:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Update clips
      env:
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
        TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
      run: python update_clips.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add clips.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update clips.json [skip ci]" && git push)
